version: '3.8'

services:
  # Frontend (Production build)
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs

  # LiveKit Agent Worker (Your working logic)
  agent-worker:
    build: ./backend
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
    command: ["python", "-m", "app.core.agent", "start"]
    volumes:
      - ./logs:/app/logs