services:
  # FastAPI Web Server - UI and API
  flo-voice-web:
    image: flo-voice-demo:latest
    build: .
    container_name: flo-voice-web
    ports:
      - "8002:8000"
    environment:
      # Only LiveKit API credentials needed for dispatching calls
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      # UI authentication
      - UI_USER_NAME=${UI_USER_NAME}
      - UI_PASSWORD=${UI_PASSWORD}
      # Python settings
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - 'logs-data:/app/logs'
    # Increased resource limits
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # Better health check using Python instead of curl
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    networks:
      - flo-voice-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flo-voice.rule=Host(`voice.a-impact.io`)"
      - "traefik.http.routers.flo-voice.entrypoints=websecure"
      - "traefik.http.routers.flo-voice.tls.certresolver=letsencrypt"
      - "traefik.http.services.flo-voice.loadbalancer.server.port=8000"
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4", "--timeout-keep-alive", "65", "--log-level", "info", "--access-log"]

  # LiveKit Agent Worker - Voice Call Handler
  flo-voice-agent:
    image: flo-voice-demo:latest
    build: .
    container_name: flo-voice-agent
    environment:
      # All credentials needed for voice processing
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - SIP_OUTBOUND_TRUNK_ID=${SIP_OUTBOUND_TRUNK_ID}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - 'logs-data:/app/logs'
    # Resource limits for agent
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - flo-voice-network
    # Override default command to run the agent
    command: ["python", "agent.py", "start"]
    healthcheck:
      disable: true

networks:
  flo-voice-network:
    driver: bridge 

volumes:
  logs-data:
    driver: local