// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvrtubvvuklbrnlpqnqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cnR1YnZ2dWtsYnJubHBxbnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNTgzNzAsImV4cCI6MjA1MTkzNDM3MH0.ExyGn7b-e5l0wxuShqR91Ns7xLAyPsr7QbUJ2jkdGGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);